#rest api example new
###
GET http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/products/5fb34b054af60d9abd905253 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json
    
{
    "name": "Brownie´s",
    "price": 200,
    "category": "Desserts",
    "image": "https://www.hola.com/imagenes/cocina/2017062096074/brownie-microondas-3-minutos-hk/0-461-970/brownie-microondas-m.jpg"
}

###
PUT http://localhost:3000/api/products/5fcd85c7c6deaf411466707b HTTP/1.1
Content-Type: application/json

{
    "name": "Chocolate´s cake",
    "price": 800,
    "category": "Desserts",
    "image": "https://2.bp.blogspot.com/-SinZR155sCg/TfY-In7I30I/AAAAAAAAAJU/5OcVIhVmDU8/s1600/chocolate-ganache.jpg"
}

###
DELETE http://localhost:3000/api/products/5fcbfea1c6deaf4114667079 HTTP/1.1
Content-Type: application/json
